### ISSUE TITLE
Problems with run.sh

### ISSUE THREAD

**Issue by gogvale** [thepack82/thepack_82_docker#5]
I tried to run the run.sh command and this appeared in my terminal screen

![image](https://user-images.githubusercontent.com/23729423/56852438-2178b580-68e1-11e9-9cbc-cb6d1ffffead.png)

Error message:

> 
> Step 1/11 : FROM java:6
>  ---> 613055f01959
> Step 2/11 : RUN apt-get update
>  ---> Running in f63b85693557
> Ign http://security.debian.org wheezy/updates Release.gpg
> Ign http://security.debian.org wheezy/updates Release
> Err http://security.debian.org wheezy/updates/main amd64 Packages
>   
> Ign http://deb.debian.org wheezy Release.gpg
> Err http://security.debian.org wheezy/updates/main amd64 Packages
>   
> Err http://security.debian.org wheezy/updates/main amd64 Packages
>   
> Ign http://deb.debian.org wheezy-updates Release.gpg
> Err http://security.debian.org wheezy/updates/main amd64 Packages
>   
> Ign http://deb.debian.org wheezy Release
> Err http://security.debian.org wheezy/updates/main amd64 Packages
>   404  Not Found
> Ign http://deb.debian.org wheezy-updates Release
> Err http://deb.debian.org wheezy/main amd64 Packages
>   
> Err http://deb.debian.org wheezy-updates/main amd64 Packages
>   
> Err http://deb.debian.org wheezy/main amd64 Packages
>   
> Err http://deb.debian.org wheezy-updates/main amd64 Packages
>   
> Err http://deb.debian.org wheezy/main amd64 Packages
>   
> Err http://deb.debian.org wheezy-updates/main amd64 Packages
>   
> Err http://deb.debian.org wheezy/main amd64 Packages
>   
> Err http://deb.debian.org wheezy-updates/main amd64 Packages
>   
> Err http://deb.debian.org wheezy/main amd64 Packages
>   404  Not Found
> Err http://deb.debian.org wheezy-updates/main amd64 Packages
>   404  Not Found
> W: Failed to fetch http://security.debian.org/dists/wheezy/updates/main/binary-amd64/Packages  404  Not Found
> 
> W: Failed to fetch http://deb.debian.org/debian/dists/wheezy/main/binary-amd64/Packages  404  Not Found
> 
> W: Failed to fetch http://deb.debian.org/debian/dists/wheezy-updates/main/binary-amd64/Packages  404  Not Found
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> The command '/bin/sh -c apt-get update' returned a non-zero code: 100
> Unable to find image 'odinms:latest' locally
> docker: Error response from daemon: pull access denied for odinms, repository does not exist or may require 'docker login'.
> See 'docker run --help'.
> 0af34687d31715140dbbb686ed0fcd861ac57bc704433938b11c54ce27607927

I wanted to learn with this project, any help would be appreciated :)

**Comment by thepack82** [comment]
It should work now.
